### ISSUE TITLE
Practica3_Equipo_Diagramas_UML

### ISSUE THREAD

**Issue by Nelsy21** [SistemasTecTlaxiaco/actividad-6-diagrama-de-clases-mana#1]
[PRACTICA3_INGENIERIA_SOFTWARE.pdf](https://github.com/SistemasTecTlaxiaco/actividad-6-diagrama-de-clases-mana/files/14718128/PRACTICA3_INGENIERIA_SOFTWARE.pdf)

**Comment by Julissamigdalia** [comment]
Buen trabajo
calificacion:20/20

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
